name = "Tayiocraft"
author = "Superd22"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12fb98b8381a47ec808c9dd20bd02aae204a43fa333ce387b377b8d9cdf3d971"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
