name = "Tayiocraft"
author = "Superd22"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535ace64623b2a23c92e87085a48d90caa93ac7dc5e0df43c8588ddb84819604"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
