name = "Tayiocraft"
author = "Superd22"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc0180136e9c4d0164eaa5c2cd4026dbf07fabccd324c06cb66f831d784d94a3"

[versions]
fabric = "0.16.3"
minecraft = "1.20.1"
